# 02.7 Overall Health by State - Rankings

1. Imports and display options
1. Data prep
1. Ranking calculations
1. Export
1. Conclusion

<div class="alert" style='background:#DCDCDC;color:#4D4D4D;padding:15px'>
    This notebook will create a system to rank each state's health in six categories (BMI, general health, doctor visits, mental health, dietary health, and physical activity) to help foster an understanding of which areas of health each state is doing well and which areas could use some improving. This data will help generate visualizations based on the analysis conducted in the previous Overall Health by State jupyter notebooks.
    </div>

## 1. Imports and display options

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
#Creating a path to the root directory for this project

path = r'C:\Users\theva\Documents\Data Analyses\BRFSS'

In [3]:
#Importing data

df = pd.read_pickle(os.path.join(path, '02 Data','Prepared Data', 'BRFSS Overall Health by State TABLEAU.pkl'))

In [4]:
#Checking df

df.shape

(385, 35)

In [5]:
#Checking df

df.head()

,location,year,BMI: Obese (BMI 30.0 - 99.8),BMI: Overweight (BMI 25.0-29.9),BMI: Normal Weight (BMI 18.5-24.9),BMI: Underweight (BMI 12.0-18.4),General health: Excellent,General health: Very good,General health: Good,General health: Fair,...,Vegetables eaten: Daily,Vegetables eaten: Not daily,Aerobic activity per week: Over 150 min,Aerobic activity per week: Under 150 min,Met physical activity guidelines: Yes,Met physical activity guidelines: No,Strength training: 2x+ per week,Strength training: 1x- per week,Physically active in last month: Yes,Physically active in last month: No
0,Alabama,2015,35.6,33.0,28.9,2.4,16.2,29.1,32.5,15.2,...,72.2,27.8,44.6,55.4,16.7,83.3,25.8,74.2,68.1,31.9
1,Alabama,2016,35.7,33.8,28.4,2.1,15.2,29.8,32.5,15.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.6,29.4
2,Alabama,2017,36.3,33.9,28.5,1.3,15.4,28.2,33.1,16.2,...,80.7,19.3,42.8,57.2,16.1,83.9,26.0,74.0,68.0,32.0
3,Alabama,2018,36.2,33.4,28.4,2.0,14.5,28.6,34.0,15.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.3,30.7
4,Alabama,2019,36.1,34.2,27.5,2.2,15.4,29.5,32.4,16.2,...,77.7,22.3,44.8,55.2,17.6,82.4,29.2,70.8,68.5,31.5

In [6]:
#Adjusting display settings

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_colwidth', None)

%matplotlib inline

# 2. Data prep

In [7]:
# Getting column names

df.columns

Index(['location', 'year', 'BMI: Obese (BMI 30.0 - 99.8)',
       'BMI: Overweight (BMI 25.0-29.9)', 'BMI: Normal Weight (BMI 18.5-24.9)',
       'BMI: Underweight (BMI 12.0-18.4)', 'General health: Excellent',
       'General health: Very good', 'General health: Good',
       'General health: Fair', 'General health: Poor',
       'Health status: Good or Better', 'Health status: Fair or Poor',
       'Doc visit: Past year', 'Doc visit: Past 2 years',
       'Doc visit: Past 5 years', 'Doc visit: 5+ years ago',
       'Doc visit: Never', 'Concentrate, remember, decide: Difficult',
       'Concentrate, remember, decide: Not difficult',
       'Bad mental health days: 0', 'Bad mental health days: 1-13',
       'Bad mental health days: 14+', 'Fruit eaten: Daily',
       'Fruit eaten: Not daily', 'Vegetables eaten: Daily',
       'Vegetables eaten: Not daily',
       'Aerobic activity per week: Over 150 min',
       'Aerobic activity per week: Under 150 min',
       'Met physical activity guidelines: Yes',
       'Met physical activity guidelines: No',
       'Strength training: 2x+ per week', 'Strength training: 1x- per week',
       'Physically active in last month: Yes',
       'Physically active in last month: No'],
      dtype='object')

In [8]:
# Dropping year, certain calculated variables, and negative response to binary question pairs, 
# i.e.: keeping 'Fruit eaten: Daily' and dropping 'Fruit eaten: Not daily'. 

df.drop(columns=['year',
                 'Health status: Good or Better',
                 'Health status: Fair or Poor',
                 'Concentrate, remember, decide: Not difficult',
                 'Fruit eaten: Not daily',
                 'Vegetables eaten: Not daily',
                 'Aerobic activity per week: Under 150 min',
                 'Met physical activity guidelines: Yes',
                 'Met physical activity guidelines: No',
                 'Strength training: 1x- per week',
                 'Physically active in last month: No'
                 ], inplace=True)

In [9]:
# Dropping national averages as they will prevent a geospatial analysis

df = df.loc[(df['location'] != 'All States and DC (median) **') &
            (df['location'] != 'All States, DC and Territories (median) **')]

In [10]:
#Checking changes

df.head()

,location,BMI: Obese (BMI 30.0 - 99.8),BMI: Overweight (BMI 25.0-29.9),BMI: Normal Weight (BMI 18.5-24.9),BMI: Underweight (BMI 12.0-18.4),General health: Excellent,General health: Very good,General health: Good,General health: Fair,General health: Poor,...,Doc visit: Never,"Concentrate, remember, decide: Difficult",Bad mental health days: 0,Bad mental health days: 1-13,Bad mental health days: 14+,Fruit eaten: Daily,Vegetables eaten: Daily,Aerobic activity per week: Over 150 min,Strength training: 2x+ per week,Physically active in last month: Yes
0,Alabama,35.6,33.0,28.9,2.4,16.2,29.1,32.5,15.2,7.0,...,1.3,15.0,NaN,NaN,NaN,51.7,72.2,44.6,25.8,68.1
1,Alabama,35.7,33.8,28.4,2.1,15.2,29.8,32.5,15.7,6.9,...,1.1,14.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.6
2,Alabama,36.3,33.9,28.5,1.3,15.4,28.2,33.1,16.2,7.1,...,1.2,15.8,NaN,NaN,NaN,55.2,80.7,42.8,26.0,68.0
3,Alabama,36.2,33.4,28.4,2.0,14.5,28.6,34.0,15.7,7.2,...,0.5,15.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.3
4,Alabama,36.1,34.2,27.5,2.2,15.4,29.5,32.4,16.2,6.5,...,0.7,16.7,58.0,24.5,17.5,53.9,77.7,44.8,29.2,68.5

In [11]:
# Making a dataframe of mean values per state

df = df.groupby('location').mean().reset_index()

# Checking dataframe
df

,location,BMI: Obese (BMI 30.0 - 99.8),BMI: Overweight (BMI 25.0-29.9),BMI: Normal Weight (BMI 18.5-24.9),BMI: Underweight (BMI 12.0-18.4),General health: Excellent,General health: Very good,General health: Good,General health: Fair,General health: Poor,...,Doc visit: Never,"Concentrate, remember, decide: Difficult",Bad mental health days: 0,Bad mental health days: 1-13,Bad mental health days: 14+,Fruit eaten: Daily,Vegetables eaten: Daily,Aerobic activity per week: Over 150 min,Strength training: 2x+ per week,Physically active in last month: Yes
0,Alabama,36.971429,33.414286,27.642857,1.942857,15.642857,29.428571,33.042857,15.542857,6.385714,...,0.900000,15.242857,58.500000,24.266667,17.233333,53.750000,77.500000,44.066667,27.000000,69.171429
1,Alaska,31.542857,35.028571,32.000000,1.450000,20.057143,33.728571,31.442857,11.200000,3.528571,...,1.440000,9.242857,62.833333,25.166667,11.966667,59.350000,81.150000,57.766667,35.466667,79.342857
2,Arizona,30.000000,35.400000,32.385714,2.228571,19.657143,31.042857,31.171429,13.571429,4.528571,...,1.014286,11.028571,60.466667,25.100000,14.433333,60.850000,78.925000,53.433333,33.266667,76.557143
3,Arkansas,36.385714,33.142857,28.500000,1.942857,15.014286,28.928571,32.371429,16.528571,7.142857,...,1.342857,15.571429,58.133333,23.900000,18.000000,53.575000,77.725000,45.433333,27.400000,68.314286
4,California,26.300000,35.900000,35.628571,2.185714,20.314286,30.171429,32.257143,13.400000,3.842857,...,1.171429,10.314286,60.400000,26.600000,13.000000,64.825000,78.400000,56.300000,33.666667,79.257143
5,Colorado,23.028571,35.714286,39.085714,2.157143,21.071429,36.414286,29.000000,10.542857,2.942857,...,1.100000,8.800000,57.700000,29.166667,13.100000,64.025000,81.675000,59.233333,36.733333,82.642857
6,Connecticut,27.757143,36.114286,34.242857,1.885714,21.942857,35.871429,28.414286,10.528571,3.214286,...,0.460000,9.142857,61.933333,25.833333,12.233333,66.000000,81.050000,53.266667,34.733333,77.400000
7,Delaware,32.928571,35.285714,30.000000,1.785714,18.671429,32.800000,31.785714,12.785714,3.942857,...,0.716667,10.942857,63.166667,23.966667,12.933333,62.425000,80.325000,48.633333,32.033333,72.528571
8,District of Columbia,23.585714,31.585714,42.800000,2.014286,26.242857,36.371429,25.157143,9.400000,2.828571,...,NaN,9.714286,52.033333,34.533333,13.400000,65.875000,83.900000,55.200000,36.300000,81.085714
9,Florida,28.116667,36.200000,33.550000,2.100000,20.650000,29.966667,30.633333,13.766667,4.983333,...,0.933333,12.300000,65.750000,21.200000,13.050000,62.833333,79.400000,51.866667,33.333333,72.450000
10,Georgia,32.485714,34.085714,31.471429,1.942857,18.971429,30.600000,32.085714,13.742857,4.614286,...,1.000000,12.014286,60.966667,24.200000,14.833333,58.125000,79.700000,47.433333,33.066667,72.814286
11,Guam,32.214286,33.557143,32.014286,2.233333,17.900000,23.957143,38.257143,15.228571,4.642857,...,1.400000,9.742857,66.500000,21.200000,12.300000,55.150000,72.525000,46.266667,33.500000,70.142857
12,Hawaii,24.242857,34.257143,38.814286,2.685714,19.742857,31.314286,34.814286,11.000000,3.128571,...,0.728571,8.371429,66.300000,22.800000,10.833333,59.725000,78.425000,55.966667,35.533333,78.528571
13,Idaho,29.400000,35.985714,32.900000,1.714286,19.942857,34.500000,30.771429,10.785714,4.000000,...,1.128571,10.885714,61.533333,24.900000,13.566667,61.675000,83.175000,55.633333,31.200000,78.442857
14,Illinois,31.928571,34.657143,31.800000,1.614286,18.757143,32.471429,32.342857,12.642857,3.771429,...,0.657143,9.014286,64.666667,23.533333,11.766667,62.700000,78.600000,50.600000,33.100000,74.942857
15,Indiana,34.271429,33.728571,30.200000,1.814286,16.400000,32.414286,32.642857,13.457143,5.085714,...,0.814286,11.585714,59.166667,25.666667,15.200000,58.150000,78.050000,45.600000,29.800000,71.928571
16,Iowa,34.657143,34.714286,29.171429,1.428571,17.257143,36.214286,32.714286,10.757143,3.071429,...,0.814286,9.414286,61.466667,25.433333,13.066667,60.200000,77.025000,49.100000,30.533333,75.471429
17,Kansas,34.100000,34.585714,29.500000,1.800000,17.785714,34.228571,32.200000,11.900000,3.900000,...,1.028571,10.785714,60.533333,25.133333,14.366667,58.400000,80.200000,49.200000,30.300000,75.271429
18,Kentucky,36.142857,33.385714,28.585714,1.885714,14.557143,30.571429,31.914286,15.642857,7.271429,...,0.980000,15.928571,58.466667,24.000000,17.533333,54.925000,79.725000,41.733333,27.266667,68.142857
19,Louisiana,36.757143,33.285714,28.057143,1.900000,17.128571,29.871429,31.357143,15.442857,6.228571,...,0.871429,16.014286,56.266667,25.733333,17.966667,52.225000,73.500000,45.366667,29.800000,69.442857
20,Maine,30.571429,35.057143,32.557143,1.785714,18.442857,36.228571,29.257143,11.857143,4.228571,...,0.250000,11.857143,63.033333,22.966667,14.000000,65.800000,85.925000,52.733333,29.333333,75.542857
21,Maryland,31.214286,35.014286,31.957143,1.814286,19.971429,35.042857,30.828571,10.985714,3.214286,...,0.733333,8.828571,61.066667,26.700000,12.233333,63.850000,79.975000,51.700000,33.700000,76.857143
22,Massachusetts,25.200000,35.457143,37.357143,2.028571,22.371429,35.228571,28.714286,10.214286,3.442857,...,0.466667,10.485714,60.800000,26.300000,12.866667,66.350000,83.100000,51.833333,31.966667,76.985714
23,Michigan,33.514286,34.671429,30.028571,1.800000,15.757143,33.700000,32.842857,12.942857,4.757143,...,0.600000,13.000000,56.433333,27.766667,15.833333,61.100000,79.275000,50.866667,31.500000,75.757143
24,Minnesota,29.371429,36.085714,32.871429,1.671429,19.785714,37.385714,30.285714,9.714286,2.842857,...,0.742857,9.200000,60.200000,27.766667,12.066667,64.775000,79.600000,54.633333,33.266667,79.414286
25,Mississippi,38.471429,33.357143,26.285714,1.900000,14.600000,28.400000,33.942857,15.842857,7.200000,...,1.033333,15.814286,64.900000,19.700000,15.466667,52.050000,75.300000,40.400000,27.133333,67.014286
26,Missouri,33.942857,33.914286,30.300000,1.842857,17.357143,33.314286,30.957143,13.185714,5.214286,...,0.985714,12.785714,60.400000,24.100000,15.433333,57.525000,80.325000,47.433333,28.366667,73.028571
27,Montana,27.114286,36.500000,34.685714,1.742857,20.028571,35.300000,29.757143,10.614286,4.257143,...,1.428571,10.800000,60.233333,25.966667,13.866667,60.850000,82.950000,58.366667,34.266667,78.585714
28,Nebraska,33.471429,35.557143,29.385714,1.585714,18.800000,35.700000,31.571429,10.742857,3.171429,...,1.157143,8.728571,62.200000,25.700000,12.100000,60.000000,78.400000,49.566667,31.933333,75.771429
29,Nevada,28.471429,37.228571,32.442857,1.900000,17.814286,28.857143,33.814286,14.600000,4.957143,...,1.528571,12.314286,59.333333,24.066667,16.600000,60.050000,77.375000,50.100000,33.333333,74.600000
30,New Hampshire,28.985714,36.214286,33.214286,1.600000,20.800000,37.428571,28.700000,9.614286,3.457143,...,NaN,10.085714,59.033333,26.900000,14.066667,66.325000,84.500000,56.300000,33.066667,78.814286
31,New Jersey,26.950000,36.750000,34.466667,1.816667,21.300000,32.450000,30.400000,12.116667,3.783333,...,0.866667,9.466667,62.550000,24.600000,12.800000,65.133333,79.166667,48.900000,32.150000,73.400000
32,New Mexico,30.714286,35.800000,31.500000,1.971429,18.471429,28.314286,33.128571,15.028571,5.028571,...,1.500000,12.771429,62.600000,23.233333,14.133333,58.825000,78.050000,54.500000,34.933333,77.000000
33,New York,26.614286,35.442857,35.728571,2.185714,20.557143,31.914286,31.428571,11.957143,4.100000,...,0.714286,9.614286,64.133333,23.400000,12.500000,64.725000,78.775000,48.866667,32.666667,73.542857
34,North Carolina,32.942857,34.942857,30.414286,1.685714,18.842857,32.100000,31.200000,12.914286,4.914286,...,0.700000,12.057143,64.700000,21.800000,13.500000,60.225000,81.925000,49.000000,30.200000,75.671429
35,North Dakota,33.471429,36.028571,29.114286,1.385714,18.128571,36.028571,32.000000,10.642857,3.185714,...,1.085714,9.014286,64.566667,23.700000,11.733333,59.550000,76.975000,46.533333,29.933333,74.714286
36,Ohio,33.885714,34.485714,29.942857,1.685714,17.257143,33.442857,31.628571,13.285714,4.385714,...,0.585714,11.928571,58.866667,25.166667,15.966667,58.425000,79.175000,48.666667,31.133333,73.328571
37,Oklahoma,35.800000,34.285714,28.085714,1.857143,15.785714,30.342857,33.157143,14.700000,6.028571,...,1.585714,14.185714,60.566667,23.100000,16.300000,51.500000,79.050000,42.133333,26.800000,69.685714
38,Oregon,29.342857,34.785714,33.885714,1.985714,18.200000,34.214286,30.757143,12.542857,4.285714,...,1.085714,12.485714,59.133333,26.066667,14.800000,64.275000,83.575000,57.933333,32.100000,80.142857
39,Pennsylvania,31.542857,35.114286,31.742857,1.614286,17.042857,34.228571,31.585714,13.014286,4.085714,...,0.700000,11.200000,61.633333,24.400000,13.966667,62.350000,80.050000,50.900000,31.200000,75.157143
40,Puerto Rico,32.271429,36.471429,29.314286,1.942857,20.271429,13.985714,32.757143,28.685714,4.314286,...,0.566667,16.314286,79.366667,9.200000,11.433333,46.000000,59.625000,27.966667,10.766667,52.342857
41,Rhode Island,28.642857,35.814286,33.857143,1.714286,19.385714,34.257143,30.700000,11.728571,3.928571,...,NaN,11.757143,60.700000,25.500000,13.833333,64.600000,79.750000,50.300000,31.200000,74.528571
42,South Carolina,34.300000,34.371429,29.471429,1.857143,18.042857,32.300000,31.200000,12.885714,5.585714,...,0.850000,13.042857,60.933333,24.233333,14.800000,56.775000,79.400000,48.666667,31.666667,72.985714
43,South Dakota,32.371429,36.142857,30.114286,1.342857,19.728571,35.957143,30.542857,10.428571,3.342857,...,1.260000,8.942857,65.633333,23.900000,10.466667,59.525000,80.100000,50.066667,30.600000,76.457143
44,Tennessee,34.700000,34.514286,29.000000,1.800000,15.885714,32.357143,31.228571,14.200000,6.314286,...,0.716667,14.242857,58.866667,24.500000,16.633333,56.725000,80.725000,46.400000,29.900000,70.900000
45,Texas,34.242857,35.171429,28.842857,1.742857,18.685714,28.157143,34.171429,14.142857,4.842857,...,1.657143,10.871429,62.500000,24.333333,13.133333,59.125000,77.850000,44.900000,32.066667,72.814286
46,Utah,27.371429,34.485714,36.042857,2.085714,21.885714,35.728571,29.585714,9.800000,3.028571,...,1.442857,10.571429,52.600000,32.000000,15.433333,64.000000,80.350000,54.700000,35.533333,81.957143
47,Vermont,27.014286,34.114286,37.085714,1.800000,20.185714,37.842857,28.928571,9.585714,3.471429,...,0.400000,9.785714,56.100000,29.300000,14.600000,67.700000,85.825000,59.966667,33.866667,80.257143
48,Virgin Islands,34.050000,31.900000,32.100000,NaN,15.550000,26.550000,37.100000,16.550000,4.300000,...,NaN,11.900000,66.900000,20.000000,13.000000,60.300000,67.800000,NaN,NaN,76.050000
49,Virginia,30.985714,35.300000,31.971429,1.785714,19.585714,34.300000,30.385714,11.928571,3.828571,...,0.814286,9.885714,62.066667,24.700000,13.200000,61.350000,81.600000,50.366667,33.533333,76.628571
50,Washington,28.071429,35.300000,34.757143,1.842857,19.342857,34.528571,31.257143,11.271429,3.557143,...,1.128571,10.185714,56.433333,29.300000,14.233333,64.875000,82.175000,58.266667,33.633333,81.685714
51,West Virginia,38.614286,33.171429,26.428571,1.785714,12.400000,29.242857,33.228571,16.900000,8.271429,...,0.740000,17.185714,58.733333,22.166667,19.166667,53.225000,79.125000,47.766667,23.200000,69.928571
52,Wisconsin,32.257143,35.485714,30.671429,1.600000,16.914286,35.814286,32.257143,11.385714,3.614286,...,0.716667,9.585714,58.833333,28.200000,12.933333,63.000000,78.525000,56.166667,31.800000,78.600000
53,Wyoming,29.557143,36.171429,32.628571,1.628571,19.828571,34.814286,30.400000,10.871429,4.057143,...,1.371429,10.057143,64.066667,22.666667,13.266667,58.775000,81.350000,54.100000,34.333333,76.200000

# 3. Ranking calculations

### 3.1 BMI ranking

<div class='alert alert-block alert-warning'>
    <b>Ranking calculation:</b><br> 
(% Obese * -1) + (% Overweight * -0.5) + (% Normal weight) + (% Underweight * -0.5)
   </div>

In [12]:
# Calculating BMI ranking 

# Making a dataframe of the variables to be used in this calculation
bmi_score = df[['location',
            'BMI: Obese (BMI 30.0 - 99.8)',
            'BMI: Overweight (BMI 25.0-29.9)',
            'BMI: Underweight (BMI 12.0-18.4)',
            'BMI: Normal Weight (BMI 18.5-24.9)'
            ]].copy()

# Applying weights to the variables
bmi_score['BMI: Obese (BMI 30.0 - 99.8)'] *= -1
bmi_score['BMI: Overweight (BMI 25.0-29.9)'] *= -0.5
bmi_score['BMI: Underweight (BMI 12.0-18.4)'] *= -0.5

# Calculating total_score as a sum of the weighted variables
bmi_score = bmi_score.fillna(bmi_score.median())
bmi_score['total_score'] = (bmi_score['BMI: Obese (BMI 30.0 - 99.8)'] +
                            bmi_score['BMI: Overweight (BMI 25.0-29.9)'] +
                            bmi_score['BMI: Underweight (BMI 12.0-18.4)'] +
                            bmi_score['BMI: Normal Weight (BMI 18.5-24.9)']
                           )
                            
# Reducing dataframe to location and total_score, sorting by total_score in descending order
bmi_rank = bmi_score[['location', 'total_score']].sort_values(by = ['total_score'], ascending = False).reset_index(drop = True)

# Calculating rank
bmi_rank['rank'] = bmi_rank['total_score'].rank(method='min', ascending = False)

# Changing rank to an integer
bmi_rank['rank'] = bmi_rank['rank'].astype(int)

# Checking dataframe
bmi_rank

C:\Users\theva\AppData\Local\Temp\ipykernel_13980\3490804841.py:17: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  bmi_score = bmi_score.fillna(bmi_score.median())

                location  total_score  rank
0   District of Columbia     2.414286     1
1               Colorado    -2.878571     2
2                 Hawaii    -3.900000     3
3          Massachusetts    -6.585714     4
4                Vermont    -7.885714     5
5                   Utah    -9.614286     6
6               New York    -9.700000     7
7             California    -9.714286     8
8                Montana   -11.550000     9
9             New Jersey   -11.766667    10
10            Washington   -11.885714    11
11           Connecticut   -12.514286    12
12          Rhode Island   -13.550000    13
13               Florida   -13.716667    14
14                Oregon   -13.842857    15
15         New Hampshire   -14.678571    16
16                 Idaho   -15.350000    17
17             Minnesota   -15.378571    18
18                Nevada   -15.592857    19
19               Wyoming   -15.828571    20
20               Arizona   -16.428571    21
21                 Maine   -16.435714    22
22              Virginia   -17.557143    23
23              Maryland   -17.671429    24
24                Alaska   -17.782143    25
25                  Guam   -18.095238    26
26            New Mexico   -18.100000    27
27          Pennsylvania   -18.164286    28
28              Illinois   -18.264286    29
29        Virgin Islands   -18.807143    30
30               Georgia   -19.028571    31
31             Wisconsin   -20.128571    32
32        North Carolina   -20.842857    33
33          South Dakota   -21.000000    34
34              Delaware   -21.464286    35
35              Missouri   -21.521429    36
36              Michigan   -21.721429    37
37               Indiana   -21.842857    38
38                  Ohio   -22.028571    39
39           Puerto Rico   -22.164286    40
40              Nebraska   -22.657143    41
41                Kansas   -22.792857    42
42        South Carolina   -22.942857    43
43          North Dakota   -23.064286    44
44                  Iowa   -23.557143    45
45                 Texas   -23.857143    46
46             Tennessee   -23.857143    47
47              Kentucky   -25.192857    48
48              Arkansas   -25.428571    49
49              Oklahoma   -25.785714    50
50             Louisiana   -26.292857    51
51               Alabama   -27.007143    52
52         West Virginia   -29.664286    53
53           Mississippi   -29.814286    54

### 3.2 General health ranking

<div class='alert alert-block alert-warning'>
    <b>Ranking calculation:</b><br> 
(% Excellent * 1.5) + (% Very good) + (% Good * 0.5) + (% Fair * 0) + (% Poor * -1)
   </div>

In [13]:
# Calculating General health ranking

# Making a dataframe of the variables to be used in this calculation
health_score = df[['location',
               'General health: Excellent',
               'General health: Very good',
               'General health: Good',
               'General health: Poor'
                ]].copy()

# Applying weights to the variables
health_score['General health: Excellent'] *= 1.5
health_score['General health: Good'] *= 0.5
health_score['General health: Poor'] *= -1

# Calculating total_score as a sum of the weighted variables
health_score = health_score.fillna(health_score.median())
health_score['total_score'] = (health_score['General health: Excellent'] +
                                  health_score['General health: Very good'] +
                                  health_score['General health: Good'] +
                                  health_score['General health: Poor']
                           )
                            
# Reducing dataframe to location and total_score, sorting by total_score in descending order
health_rank = health_score[['location', 'total_score']].sort_values(by = ['total_score'], ascending = False).reset_index(drop = True)

# Calculating rank
health_rank['rank'] = health_rank['total_score'].rank(method='min', ascending = False)

# Changing rank to an integer
health_rank['rank'] = health_rank['rank'].astype(int)

# Checking dataframe
health_rank

C:\Users\theva\AppData\Local\Temp\ipykernel_13980\2178899999.py:17: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  health_score = health_score.fillna(health_score.median())

                location  total_score  rank
0   District of Columbia    85.485714     1
1                   Utah    80.321429     2
2            Connecticut    79.778571     3
3          Massachusetts    79.700000     4
4               Colorado    79.578571     5
5          New Hampshire    79.521429     6
6              Minnesota    79.364286     7
7                Vermont    79.114286     8
8           South Dakota    77.478571     9
9               Maryland    77.200000    10
10              Nebraska    76.514286    11
11          North Dakota    76.035714    12
12                Alaska    76.007143    13
13               Montana    75.964286    14
14            New Jersey    75.816667    15
15                 Idaho    75.800000    16
16               Wyoming    75.700000    17
17            Washington    75.614286    18
18                  Iowa    75.385714    19
19                Hawaii    75.207143    20
20              Virginia    75.042857    21
21          Rhode Island    74.757143    22
22              New York    74.364286    23
23                 Maine    74.292857    24
24             Wisconsin    73.700000    25
25                Kansas    73.107143    26
26              Illinois    73.007143    27
27            California    72.928571    28
28              Delaware    72.757143    29
29                Oregon    72.607143    30
30               Arizona    71.585714    31
31          Pennsylvania    71.500000    32
32               Florida    71.275000    33
33        North Carolina    71.050000    34
34                  Ohio    70.757143    35
35               Georgia    70.485714    36
36              Missouri    69.614286    37
37        South Carolina    69.378571    38
38              Michigan    69.000000    39
39                 Texas    68.428571    40
40               Indiana    68.250000    41
41            New Mexico    67.557143    42
42                Nevada    67.528571    43
43             Tennessee    65.485714    44
44                  Guam    65.292857    45
45             Louisiana    65.014286    46
46              Oklahoma    64.571429    47
47        Virgin Islands    64.125000    48
48               Alabama    63.028571    49
49              Kentucky    61.092857    50
50              Arkansas    60.492857    51
51           Mississippi    60.071429    52
52           Puerto Rico    56.457143    53
53         West Virginia    56.185714    54

### 3.3 Doctor visits ranking

<div class='alert alert-block alert-warning'>
    <b>Ranking calculation:</b><br> 
(% Past year) + (% Past 2 years * 0) + (% Past 5 years * -0.5) + (% 5+ years ago * -1) + (% Never * -2)
   </div>

In [14]:
# Calculating Doctor visits ranking

# Making a dataframe of the variables to be used in this calculation
doc_score = df[['location',
                'Doc visit: Past year',
                'Doc visit: Past 5 years',
                'Doc visit: 5+ years ago',
                'Doc visit: Never'
                ]].copy()

# Applying weights to the variables
doc_score['Doc visit: Past 5 years'] *= -0.5
doc_score['Doc visit: 5+ years ago'] *= -1
doc_score['Doc visit: Never'] *= -2

# Calculating total_score as a sum of the weighted variables
doc_score = doc_score.fillna(doc_score.median())
doc_score['total_score'] = (doc_score['Doc visit: Past year'] +
                            doc_score['Doc visit: Past 5 years'] +
                            doc_score['Doc visit: 5+ years ago'] +
                            doc_score['Doc visit: Never']
                           )
                            
# Reducing dataframe to location and total_score, sorting by total_score in descending order
doc_rank = doc_score[['location', 'total_score']].sort_values(by = ['total_score'], ascending = False).reset_index(drop = True)

# Calculating rank
doc_rank['rank'] = doc_rank['total_score'].rank(method='min', ascending = False)

# Changing rank to an integer
doc_rank['rank'] = doc_rank['rank'].astype(int)

# Checking dataframe
doc_rank

C:\Users\theva\AppData\Local\Temp\ipykernel_13980\3982562383.py:17: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  doc_score = doc_score.fillna(doc_score.median())

                location  total_score  rank
0           Rhode Island    75.423810     1
1          Massachusetts    72.066667     2
2            Puerto Rico    71.645238     3
3               Delaware    69.923810     4
4            Connecticut    69.780000     5
5             New Jersey    69.700000     6
6               New York    69.442857     7
7          West Virginia    69.370000     8
8   District of Columbia    69.138095     9
9               Maryland    68.404762    10
10        North Carolina    67.307143    11
11          Pennsylvania    66.785714    12
12              Virginia    66.592857    13
13              Michigan    66.550000    14
14                 Maine    66.157143    15
15               Florida    65.800000    16
16             Louisiana    65.600000    17
17                Hawaii    64.900000    18
18         New Hampshire    64.895238    19
19              Kentucky    64.882857    20
20                  Ohio    64.792857    21
21           Mississippi    64.783333    22
22              Illinois    64.142857    23
23               Georgia    63.750000    24
24               Alabama    63.564286    25
25             Tennessee    63.416667    26
26                  Iowa    63.100000    27
27        South Carolina    62.050000    28
28             Wisconsin    62.030952    29
29               Vermont    61.878571    30
30              Arkansas    61.400000    31
31             Minnesota    60.857143    32
32              Missouri    60.464286    33
33               Indiana    59.185714    34
34                Kansas    59.021429    35
35          South Dakota    58.830000    36
36               Arizona    57.050000    37
37        Virgin Islands    56.266667    38
38              Oklahoma    56.264286    39
39              Nebraska    55.742857    40
40            California    55.342857    41
41                 Texas    55.207143    42
42                Oregon    54.628571    43
43                Nevada    54.335714    44
44            Washington    54.171429    45
45               Montana    52.935714    46
46                  Guam    52.542857    47
47          North Dakota    51.814286    48
48              Colorado    50.985714    49
49            New Mexico    50.921429    50
50                  Utah    48.885714    51
51                 Idaho    48.807143    52
52               Wyoming    47.942857    53
53                Alaska    43.948571    54

### 3.4 Mental health ranking

<div class='alert alert-block alert-warning'>
    <b>Ranking calculation:</b><br> 
(% 0 bad mental health days * 1) + (% 1-13 bad mental health days * 0) + (% 14+ bad mental health days * -1) + (% Difficulty concentrating, deciding, remembering * -1)
   </div>

In [15]:
# Calculating Mental health ranking

# Making a dataframe of the variables to be used in this calculation
mhealth_score = df[['location',
                    'Concentrate, remember, decide: Difficult',
                    'Bad mental health days: 0',
                    'Bad mental health days: 14+'
                   ]].copy()

# Applying weights to the variables
mhealth_score['Bad mental health days: 14+'] *= -1
mhealth_score['Concentrate, remember, decide: Difficult'] *= -1

# Calculating total_score as a sum of the weighted variables
mhealth_score = mhealth_score.fillna(mhealth_score.median())
mhealth_score['total_score'] = (mhealth_score['Concentrate, remember, decide: Difficult'] +
                                mhealth_score['Bad mental health days: 0'] +
                                mhealth_score['Bad mental health days: 14+']
                               )
                            
# Reducing dataframe to location and total_score, sorting by total_score in descending order
mhealth_rank = mhealth_score[['location', 'total_score']].sort_values(by = ['total_score'], ascending = False).reset_index(drop = True)

# Calculating rank
mhealth_rank['rank'] = mhealth_rank['total_score'].rank(method='min', ascending = False)

# Changing rank to an integer
mhealth_rank['rank'] = mhealth_rank['rank'].astype(int)

# Checking dataframe
mhealth_rank

C:\Users\theva\AppData\Local\Temp\ipykernel_13980\4172568223.py:15: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mhealth_score = mhealth_score.fillna(mhealth_score.median())

                location  total_score  rank
0            Puerto Rico    51.619048     1
1                 Hawaii    47.095238     2
2           South Dakota    46.223810     3
3                   Guam    44.457143     4
4               Illinois    43.885714     5
5           North Dakota    43.819048     6
6               New York    42.019048     7
7         Virgin Islands    42.000000     8
8                 Alaska    41.623810     9
9               Nebraska    41.371429    10
10               Wyoming    40.742857    11
11           Connecticut    40.557143    12
12               Florida    40.400000    13
13            New Jersey    40.283333    14
14              Maryland    40.004762    15
15              Delaware    39.290476    16
16        North Carolina    39.142857    17
17                  Iowa    38.985714    18
18              Virginia    38.980952    19
19             Minnesota    38.933333    20
20                 Texas    38.495238    21
21         Massachusetts    37.447619    22
22                 Maine    37.176190    23
23            California    37.085714    24
24                 Idaho    37.080952    25
25          Pennsylvania    36.466667    26
26             Wisconsin    36.314286    27
27              Colorado    35.800000    28
28            New Mexico    35.695238    29
29               Montana    35.566667    30
30                Kansas    35.380952    31
31          Rhode Island    35.109524    32
32               Arizona    35.004762    33
33         New Hampshire    34.880952    34
34               Georgia    34.119048    35
35           Mississippi    33.619048    36
36        South Carolina    33.090476    37
37               Indiana    32.380952    38
38              Missouri    32.180952    39
39            Washington    32.014286    40
40                Oregon    31.847619    41
41               Vermont    31.714286    42
42                  Ohio    30.971429    43
43                Nevada    30.419048    44
44              Oklahoma    30.080952    45
45  District of Columbia    28.919048    46
46             Tennessee    27.990476    47
47              Michigan    27.600000    48
48                  Utah    26.595238    49
49               Alabama    26.023810    50
50              Kentucky    25.004762    51
51              Arkansas    24.561905    52
52         West Virginia    22.380952    53
53             Louisiana    22.285714    54

### 3.5 Dietary health ranking

<div class='alert alert-block alert-warning'>
    <b>Ranking calculation:</b><br> 
(% Daily fruit eaters) + (% Daily vegetable eaters)
   </div>

In [16]:
# Calculating Dietary health ranking

# Making a dataframe of the variables to be used in this calculation
dhealth_score = df[['location',
                    'Fruit eaten: Daily',
                    'Vegetables eaten: Daily'
                   ]].copy()

# No weight applied

# Calculating total_score as a sum of the weighted variables
dhealth_score = dhealth_score.fillna(dhealth_score.median())
dhealth_score['total_score'] = (dhealth_score['Fruit eaten: Daily'] +
                                dhealth_score['Vegetables eaten: Daily']
                               )
                            
# Reducing dataframe to location and total_score, sorting by total_score in descending order
dhealth_rank = dhealth_score[['location', 'total_score']].sort_values(by = ['total_score'], ascending = False).reset_index(drop = True)

# Calculating rank
dhealth_rank['rank'] = dhealth_rank['total_score'].rank(method='min', ascending = False)

# Changing rank to an integer
dhealth_rank['rank'] = dhealth_rank['rank'].astype(int)

# Checking dataframe
dhealth_rank

C:\Users\theva\AppData\Local\Temp\ipykernel_13980\1920869745.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dhealth_score = dhealth_score.fillna(dhealth_score.median())

                location  total_score  rank
0                Vermont   153.525000     1
1                  Maine   151.725000     2
2          New Hampshire   150.825000     3
3   District of Columbia   149.775000     4
4          Massachusetts   149.450000     5
5                 Oregon   147.850000     6
6             Washington   147.050000     7
7            Connecticut   147.050000     7
8               Colorado   145.700000     9
9                  Idaho   144.850000    10
10             Minnesota   144.375000    11
11                  Utah   144.350000    12
12          Rhode Island   144.350000    12
13            New Jersey   144.300000    14
14              Maryland   143.825000    15
15               Montana   143.800000    16
16              New York   143.500000    17
17            California   143.225000    18
18              Virginia   142.950000    19
19              Delaware   142.750000    20
20          Pennsylvania   142.400000    21
21               Florida   142.233333    22
22        North Carolina   142.150000    23
23             Wisconsin   141.525000    24
24              Illinois   141.300000    25
25                Alaska   140.500000    26
26              Michigan   140.375000    27
27               Wyoming   140.125000    28
28               Arizona   139.775000    29
29          South Dakota   139.625000    30
30                Kansas   138.600000    31
31              Nebraska   138.400000    32
32                Hawaii   138.150000    33
33              Missouri   137.850000    34
34               Georgia   137.825000    35
35                  Ohio   137.600000    36
36             Tennessee   137.450000    37
37                Nevada   137.425000    38
38                  Iowa   137.225000    39
39                 Texas   136.975000    40
40            New Mexico   136.875000    41
41          North Dakota   136.525000    42
42               Indiana   136.200000    43
43        South Carolina   136.175000    44
44              Kentucky   134.650000    45
45         West Virginia   132.350000    46
46              Arkansas   131.300000    47
47               Alabama   131.250000    48
48              Oklahoma   130.550000    49
49        Virgin Islands   128.100000    50
50                  Guam   127.675000    51
51           Mississippi   127.350000    52
52             Louisiana   125.725000    53
53           Puerto Rico   105.625000    54

### 3.6 Physical activity ranking

<div class='alert alert-block alert-warning'>
    <b>Ranking calculation:</b><br> 
(% Aerobically active 150 min per week * 1) + (% Strength train 2x per week * 1) + (% Physically active in last month * 0.5)
   </div>

In [17]:
# Calculating Physical activity ranking

# Making a dataframe of the variables to be used in this calculation
activity_score = df[['location',
                     'Aerobic activity per week: Over 150 min',
                     'Strength training: 2x+ per week',
                     'Physically active in last month: Yes'
                   ]].copy()

# Applying weights to the variables
activity_score['Physically active in last month: Yes'] *= 0.5

# Calculating total_score as a sum of the weighted variables
activity_score = activity_score.fillna(activity_score.median())
activity_score['total_score'] = (activity_score['Aerobic activity per week: Over 150 min'] +
                                 activity_score['Strength training: 2x+ per week'] +
                                 activity_score['Physically active in last month: Yes']
                               )
                            
# Reducing dataframe to location and total_score, sorting by total_score in descending order
activity_rank = activity_score[['location', 'total_score']].sort_values(by = ['total_score'], ascending = False).reset_index(drop = True)

# Calculating rank
activity_rank['rank'] = activity_rank['total_score'].rank(method='min', ascending = False)

# Changing rank to an integer
activity_rank['rank'] = activity_rank['rank'].astype(int)

# Checking dataframe
activity_rank

C:\Users\theva\AppData\Local\Temp\ipykernel_13980\3096664006.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  activity_score = activity_score.fillna(activity_score.median())

                location  total_score  rank
0               Colorado   137.288095     1
1                Vermont   133.961905     2
2                 Alaska   132.904762     3
3             Washington   132.742857     4
4   District of Columbia   132.042857     5
5                Montana   131.926190     6
6                   Utah   131.211905     7
7                 Hawaii   130.764286     8
8                 Oregon   130.104762     9
9             California   129.595238    10
10         New Hampshire   128.773810    11
11            New Mexico   127.933333    12
12             Minnesota   127.607143    13
13             Wisconsin   127.266667    14
14           Connecticut   126.700000    15
15               Wyoming   126.533333    16
16                 Idaho   126.054762    17
17               Arizona   124.978571    18
18              Maryland   123.828571    19
19         Massachusetts   122.292857    20
20              Virginia   122.214286    21
21               Florida   121.425000    22
22              Illinois   121.171429    23
23                Nevada   120.733333    24
24        Virgin Islands   120.358333    25
25              Michigan   120.245238    26
26                 Maine   119.838095    27
27          Pennsylvania   119.678571    28
28              Nebraska   119.385714    29
29          South Dakota   118.895238    30
30          Rhode Island   118.764286    31
31              New York   118.304762    32
32            New Jersey   117.750000    33
33                  Iowa   117.369048    34
34                Kansas   117.135714    35
35        North Carolina   117.035714    36
36              Delaware   116.930952    37
37               Georgia   116.907143    38
38        South Carolina   116.826190    39
39                  Ohio   116.464286    40
40                  Guam   114.838095    41
41          North Dakota   113.823810    42
42                 Texas   113.373810    43
43              Missouri   112.314286    44
44             Tennessee   111.750000    45
45               Indiana   111.364286    46
46             Louisiana   109.888095    47
47              Arkansas   106.990476    48
48         West Virginia   105.930952    49
49               Alabama   105.652381    50
50              Oklahoma   103.776190    51
51              Kentucky   103.071429    52
52           Mississippi   101.040476    53
53           Puerto Rico    64.904762    54

### 3.7 Total ranking
Ranking calculation:  
BMI score + General health score + Doctor visits score + Mental health score + Dietary health score + Physical activity score

In [18]:
# Making a dataframe of BMI, general health, mental health, dietary health, doctor visits, and physical activity scores and ranks

# Creating data from from a copy of bmi_rank
total_rank = bmi_rank.copy()
# Changing score and rank to reflect origin dataframe
total_rank.rename(columns={'total_score': "bmi_score", "rank": "bmi_rank"}, inplace = True)

# Merging with health_rank
total_rank = pd.merge(total_rank, health_rank, how='left', left_on=['location'], right_on=['location'])
# Changing score and rank to reflect origin dataframe
total_rank.rename(columns={'total_score': "general_health_score", "rank": "general_health_rank"}, inplace = True)

# Merging with mhealth_rank
total_rank = pd.merge(total_rank, mhealth_rank, how='left', left_on=['location'], right_on=['location'])
# Changing score and rank to reflect origin dataframe
total_rank.rename(columns={'total_score': "mental_health_score", "rank": "mental_health_rank"}, inplace = True)

# Merging with dhealth_rank
total_rank = pd.merge(total_rank, dhealth_rank, how='left', left_on=['location'], right_on=['location'])
# Changing score and rank to reflect origin dataframe
total_rank.rename(columns={'total_score': "dietary_health_score", "rank": "dietary_health_rank"}, inplace = True)

# Merging with doc_rank
total_rank = pd.merge(total_rank, doc_rank, how='left', left_on=['location'], right_on=['location'])
# Changing score and rank to reflect origin dataframe
total_rank.rename(columns={'total_score': "doctor_visits_score", "rank": "doctor_visits_rank"}, inplace = True)

# Merging with activity_rank
total_rank = pd.merge(total_rank, activity_rank, how='left', left_on=['location'], right_on=['location'])
# Changing score and rank to reflect origin dataframe
total_rank.rename(columns={'total_score': "physical_activity_score", "rank": "physical_activity_rank"}, inplace = True)

# Checking dataframe
total_rank

,location,bmi_score,bmi_rank,general_health_score,general_health_rank,mental_health_score,mental_health_rank,dietary_health_score,dietary_health_rank,doctor_visits_score,doctor_visits_rank,physical_activity_score,physical_activity_rank
0,District of Columbia,2.414286,1,85.485714,1,28.919048,46,149.775000,4,69.138095,9,132.042857,5
1,Colorado,-2.878571,2,79.578571,5,35.800000,28,145.700000,9,50.985714,49,137.288095,1
2,Hawaii,-3.900000,3,75.207143,20,47.095238,2,138.150000,33,64.900000,18,130.764286,8
3,Massachusetts,-6.585714,4,79.700000,4,37.447619,22,149.450000,5,72.066667,2,122.292857,20
4,Vermont,-7.885714,5,79.114286,8,31.714286,42,153.525000,1,61.878571,30,133.961905,2
5,Utah,-9.614286,6,80.321429,2,26.595238,49,144.350000,12,48.885714,51,131.211905,7
6,New York,-9.700000,7,74.364286,23,42.019048,7,143.500000,17,69.442857,7,118.304762,32
7,California,-9.714286,8,72.928571,28,37.085714,24,143.225000,18,55.342857,41,129.595238,10
8,Montana,-11.550000,9,75.964286,14,35.566667,30,143.800000,16,52.935714,46,131.926190,6
9,New Jersey,-11.766667,10,75.816667,15,40.283333,14,144.300000,14,69.700000,6,117.750000,33
10,Washington,-11.885714,11,75.614286,18,32.014286,40,147.050000,7,54.171429,45,132.742857,4
11,Connecticut,-12.514286,12,79.778571,3,40.557143,12,147.050000,7,69.780000,5,126.700000,15
12,Rhode Island,-13.550000,13,74.757143,22,35.109524,32,144.350000,12,75.423810,1,118.764286,31
13,Florida,-13.716667,14,71.275000,33,40.400000,13,142.233333,22,65.800000,16,121.425000,22
14,Oregon,-13.842857,15,72.607143,30,31.847619,41,147.850000,6,54.628571,43,130.104762,9
15,New Hampshire,-14.678571,16,79.521429,6,34.880952,34,150.825000,3,64.895238,19,128.773810,11
16,Idaho,-15.350000,17,75.800000,16,37.080952,25,144.850000,10,48.807143,52,126.054762,17
17,Minnesota,-15.378571,18,79.364286,7,38.933333,20,144.375000,11,60.857143,32,127.607143,13
18,Nevada,-15.592857,19,67.528571,43,30.419048,44,137.425000,38,54.335714,44,120.733333,24
19,Wyoming,-15.828571,20,75.700000,17,40.742857,11,140.125000,28,47.942857,53,126.533333,16
20,Arizona,-16.428571,21,71.585714,31,35.004762,33,139.775000,29,57.050000,37,124.978571,18
21,Maine,-16.435714,22,74.292857,24,37.176190,23,151.725000,2,66.157143,15,119.838095,27
22,Virginia,-17.557143,23,75.042857,21,38.980952,19,142.950000,19,66.592857,13,122.214286,21
23,Maryland,-17.671429,24,77.200000,10,40.004762,15,143.825000,15,68.404762,10,123.828571,19
24,Alaska,-17.782143,25,76.007143,13,41.623810,9,140.500000,26,43.948571,54,132.904762,3
25,Guam,-18.095238,26,65.292857,45,44.457143,4,127.675000,51,52.542857,47,114.838095,41
26,New Mexico,-18.100000,27,67.557143,42,35.695238,29,136.875000,41,50.921429,50,127.933333,12
27,Pennsylvania,-18.164286,28,71.500000,32,36.466667,26,142.400000,21,66.785714,12,119.678571,28
28,Illinois,-18.264286,29,73.007143,27,43.885714,5,141.300000,25,64.142857,23,121.171429,23
29,Virgin Islands,-18.807143,30,64.125000,48,42.000000,8,128.100000,50,56.266667,38,120.358333,25
30,Georgia,-19.028571,31,70.485714,36,34.119048,35,137.825000,35,63.750000,24,116.907143,38
31,Wisconsin,-20.128571,32,73.700000,25,36.314286,27,141.525000,24,62.030952,29,127.266667,14
32,North Carolina,-20.842857,33,71.050000,34,39.142857,17,142.150000,23,67.307143,11,117.035714,36
33,South Dakota,-21.000000,34,77.478571,9,46.223810,3,139.625000,30,58.830000,36,118.895238,30
34,Delaware,-21.464286,35,72.757143,29,39.290476,16,142.750000,20,69.923810,4,116.930952,37
35,Missouri,-21.521429,36,69.614286,37,32.180952,39,137.850000,34,60.464286,33,112.314286,44
36,Michigan,-21.721429,37,69.000000,39,27.600000,48,140.375000,27,66.550000,14,120.245238,26
37,Indiana,-21.842857,38,68.250000,41,32.380952,38,136.200000,43,59.185714,34,111.364286,46
38,Ohio,-22.028571,39,70.757143,35,30.971429,43,137.600000,36,64.792857,21,116.464286,40
39,Puerto Rico,-22.164286,40,56.457143,53,51.619048,1,105.625000,54,71.645238,3,64.904762,54
40,Nebraska,-22.657143,41,76.514286,11,41.371429,10,138.400000,32,55.742857,40,119.385714,29
41,Kansas,-22.792857,42,73.107143,26,35.380952,31,138.600000,31,59.021429,35,117.135714,35
42,South Carolina,-22.942857,43,69.378571,38,33.090476,37,136.175000,44,62.050000,28,116.826190,39
43,North Dakota,-23.064286,44,76.035714,12,43.819048,6,136.525000,42,51.814286,48,113.823810,42
44,Iowa,-23.557143,45,75.385714,19,38.985714,18,137.225000,39,63.100000,27,117.369048,34
45,Texas,-23.857143,46,68.428571,40,38.495238,21,136.975000,40,55.207143,42,113.373810,43
46,Tennessee,-23.857143,47,65.485714,44,27.990476,47,137.450000,37,63.416667,26,111.750000,45
47,Kentucky,-25.192857,48,61.092857,50,25.004762,51,134.650000,45,64.882857,20,103.071429,52
48,Arkansas,-25.428571,49,60.492857,51,24.561905,52,131.300000,47,61.400000,31,106.990476,48
49,Oklahoma,-25.785714,50,64.571429,47,30.080952,45,130.550000,49,56.264286,39,103.776190,51
50,Louisiana,-26.292857,51,65.014286,46,22.285714,54,125.725000,53,65.600000,17,109.888095,47
51,Alabama,-27.007143,52,63.028571,49,26.023810,50,131.250000,48,63.564286,25,105.652381,50
52,West Virginia,-29.664286,53,56.185714,54,22.380952,53,132.350000,46,69.370000,8,105.930952,49
53,Mississippi,-29.814286,54,60.071429,52,33.619048,36,127.350000,52,64.783333,22,101.040476,53

In [19]:
# Calculating total ranking across all variables

# Finding mean rank per state
total_rank['ave_rank'] = ((total_rank['bmi_rank'] +
                           total_rank['general_health_rank'] +
                           total_rank['mental_health_rank'] +
                           total_rank['dietary_health_rank'] +
                           total_rank['doctor_visits_rank'] +
                           total_rank['physical_activity_rank'])/6
                          )

# Calculating rank
total_rank['overall_health_rank'] = total_rank['ave_rank'].rank(method='min')

# Changing rank to an integer
total_rank['overall_health_rank'] = total_rank['overall_health_rank'].astype(int)

# Sorting by overall_health_rank
total_rank = total_rank.sort_values(by = ['overall_health_rank'], ascending = True).reset_index(drop = True)

# Checking dataframe
total_rank

,location,bmi_score,bmi_rank,general_health_score,general_health_rank,mental_health_score,mental_health_rank,dietary_health_score,dietary_health_rank,doctor_visits_score,doctor_visits_rank,physical_activity_score,physical_activity_rank,ave_rank,overall_health_rank
0,Connecticut,-12.514286,12,79.778571,3,40.557143,12,147.050000,7,69.780000,5,126.700000,15,9.000000,1
1,Massachusetts,-6.585714,4,79.700000,4,37.447619,22,149.450000,5,72.066667,2,122.292857,20,9.500000,2
2,District of Columbia,2.414286,1,85.485714,1,28.919048,46,149.775000,4,69.138095,9,132.042857,5,11.000000,3
3,Hawaii,-3.900000,3,75.207143,20,47.095238,2,138.150000,33,64.900000,18,130.764286,8,14.000000,4
4,Vermont,-7.885714,5,79.114286,8,31.714286,42,153.525000,1,61.878571,30,133.961905,2,14.666667,5
5,New Hampshire,-14.678571,16,79.521429,6,34.880952,34,150.825000,3,64.895238,19,128.773810,11,14.833333,6
6,New Jersey,-11.766667,10,75.816667,15,40.283333,14,144.300000,14,69.700000,6,117.750000,33,15.333333,7
7,New York,-9.700000,7,74.364286,23,42.019048,7,143.500000,17,69.442857,7,118.304762,32,15.500000,8
8,Maryland,-17.671429,24,77.200000,10,40.004762,15,143.825000,15,68.404762,10,123.828571,19,15.500000,8
9,Colorado,-2.878571,2,79.578571,5,35.800000,28,145.700000,9,50.985714,49,137.288095,1,15.666667,10
10,Minnesota,-15.378571,18,79.364286,7,38.933333,20,144.375000,11,60.857143,32,127.607143,13,16.833333,11
11,Rhode Island,-13.550000,13,74.757143,22,35.109524,32,144.350000,12,75.423810,1,118.764286,31,18.500000,12
12,Maine,-16.435714,22,74.292857,24,37.176190,23,151.725000,2,66.157143,15,119.838095,27,18.833333,13
13,Virginia,-17.557143,23,75.042857,21,38.980952,19,142.950000,19,66.592857,13,122.214286,21,19.333333,14
14,Florida,-13.716667,14,71.275000,33,40.400000,13,142.233333,22,65.800000,16,121.425000,22,20.000000,15
15,Montana,-11.550000,9,75.964286,14,35.566667,30,143.800000,16,52.935714,46,131.926190,6,20.166667,16
16,Washington,-11.885714,11,75.614286,18,32.014286,40,147.050000,7,54.171429,45,132.742857,4,20.833333,17
17,Utah,-9.614286,6,80.321429,2,26.595238,49,144.350000,12,48.885714,51,131.211905,7,21.166667,18
18,California,-9.714286,8,72.928571,28,37.085714,24,143.225000,18,55.342857,41,129.595238,10,21.500000,19
19,Alaska,-17.782143,25,76.007143,13,41.623810,9,140.500000,26,43.948571,54,132.904762,3,21.666667,20
20,Illinois,-18.264286,29,73.007143,27,43.885714,5,141.300000,25,64.142857,23,121.171429,23,22.000000,21
21,Idaho,-15.350000,17,75.800000,16,37.080952,25,144.850000,10,48.807143,52,126.054762,17,22.833333,22
22,Delaware,-21.464286,35,72.757143,29,39.290476,16,142.750000,20,69.923810,4,116.930952,37,23.500000,23
23,South Dakota,-21.000000,34,77.478571,9,46.223810,3,139.625000,30,58.830000,36,118.895238,30,23.666667,24
24,Oregon,-13.842857,15,72.607143,30,31.847619,41,147.850000,6,54.628571,43,130.104762,9,24.000000,25
25,Wyoming,-15.828571,20,75.700000,17,40.742857,11,140.125000,28,47.942857,53,126.533333,16,24.166667,26
26,Pennsylvania,-18.164286,28,71.500000,32,36.466667,26,142.400000,21,66.785714,12,119.678571,28,24.500000,27
27,Wisconsin,-20.128571,32,73.700000,25,36.314286,27,141.525000,24,62.030952,29,127.266667,14,25.166667,28
28,North Carolina,-20.842857,33,71.050000,34,39.142857,17,142.150000,23,67.307143,11,117.035714,36,25.666667,29
29,Nebraska,-22.657143,41,76.514286,11,41.371429,10,138.400000,32,55.742857,40,119.385714,29,27.166667,30
30,Arizona,-16.428571,21,71.585714,31,35.004762,33,139.775000,29,57.050000,37,124.978571,18,28.166667,31
31,Iowa,-23.557143,45,75.385714,19,38.985714,18,137.225000,39,63.100000,27,117.369048,34,30.333333,32
32,Michigan,-21.721429,37,69.000000,39,27.600000,48,140.375000,27,66.550000,14,120.245238,26,31.833333,33
33,North Dakota,-23.064286,44,76.035714,12,43.819048,6,136.525000,42,51.814286,48,113.823810,42,32.333333,34
34,Virgin Islands,-18.807143,30,64.125000,48,42.000000,8,128.100000,50,56.266667,38,120.358333,25,33.166667,35
35,Georgia,-19.028571,31,70.485714,36,34.119048,35,137.825000,35,63.750000,24,116.907143,38,33.166667,35
36,Kansas,-22.792857,42,73.107143,26,35.380952,31,138.600000,31,59.021429,35,117.135714,35,33.333333,37
37,New Mexico,-18.100000,27,67.557143,42,35.695238,29,136.875000,41,50.921429,50,127.933333,12,33.500000,38
38,Puerto Rico,-22.164286,40,56.457143,53,51.619048,1,105.625000,54,71.645238,3,64.904762,54,34.166667,39
39,Nevada,-15.592857,19,67.528571,43,30.419048,44,137.425000,38,54.335714,44,120.733333,24,35.333333,40
40,Ohio,-22.028571,39,70.757143,35,30.971429,43,137.600000,36,64.792857,21,116.464286,40,35.666667,41
41,Guam,-18.095238,26,65.292857,45,44.457143,4,127.675000,51,52.542857,47,114.838095,41,35.666667,41
42,Missouri,-21.521429,36,69.614286,37,32.180952,39,137.850000,34,60.464286,33,112.314286,44,37.166667,43
43,South Carolina,-22.942857,43,69.378571,38,33.090476,37,136.175000,44,62.050000,28,116.826190,39,38.166667,44
44,Texas,-23.857143,46,68.428571,40,38.495238,21,136.975000,40,55.207143,42,113.373810,43,38.666667,45
45,Indiana,-21.842857,38,68.250000,41,32.380952,38,136.200000,43,59.185714,34,111.364286,46,40.000000,46
46,Tennessee,-23.857143,47,65.485714,44,27.990476,47,137.450000,37,63.416667,26,111.750000,45,41.000000,47
47,West Virginia,-29.664286,53,56.185714,54,22.380952,53,132.350000,46,69.370000,8,105.930952,49,43.833333,48
48,Kentucky,-25.192857,48,61.092857,50,25.004762,51,134.650000,45,64.882857,20,103.071429,52,44.333333,49
49,Louisiana,-26.292857,51,65.014286,46,22.285714,54,125.725000,53,65.600000,17,109.888095,47,44.666667,50
50,Mississippi,-29.814286,54,60.071429,52,33.619048,36,127.350000,52,64.783333,22,101.040476,53,44.833333,51
51,Alabama,-27.007143,52,63.028571,49,26.023810,50,131.250000,48,63.564286,25,105.652381,50,45.666667,52
52,Arkansas,-25.428571,49,60.492857,51,24.561905,52,131.300000,47,61.400000,31,106.990476,48,46.333333,53
53,Oklahoma,-25.785714,50,64.571429,47,30.080952,45,130.550000,49,56.264286,39,103.776190,51,46.833333,54

# 4. Export

In [20]:
# Exporting total_rank to csv

total_rank.to_csv(os.path.join(path, '02 Data','Prepared Data', 'BRFSS Overall Health by State - Rankings.csv'))

# 5. Conclusion

<div class='alert alert-block alert-warning'>
    <b>Summary</b><br><br>
    <li>No state scored high across the board.
    <li>Every state has areas that could be improved upon.
    <li>Some states have fewer areas to improve upon than others. I.e., the District of Columbia ranked in the top 5 for 4 categories, but 46th for mental health.
    <li>Fine tuning the weight system for question responses may yield more accurate calulations.
</div>

<div class='alert alert-block alert-success'>
    <b>Next steps</b><br><br>
    <li><b>Make a dashboard for state health statistics and ranks</b> based on the findings of this and previous analyses.
    <li>Research methods to more accurately weigh question responses and health categories.
    <li>Start preparations for Overall Health by Demographic analysis.
   </div>